// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package query

import (
	"context"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (
	filename
) VALUES (
	?
)
RETURNING id
`

func (q *Queries) CreateDocument(ctx context.Context, filename string) (int64, error) {
	row := q.queryRow(ctx, q.createDocumentStmt, createDocument, filename)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertChunk = `-- name: InsertChunk :exec
INSERT INTO chunks (
	id,
	document_id,
	chunk_index,
	chunk_count,
	text
) VALUES (?,?,?,?,?)
`

type InsertChunkParams struct {
	ID         int64
	DocumentID int64
	ChunkIndex int64
	ChunkCount int64
	Text       string
}

func (q *Queries) InsertChunk(ctx context.Context, arg InsertChunkParams) error {
	_, err := q.exec(ctx, q.insertChunkStmt, insertChunk,
		arg.ID,
		arg.DocumentID,
		arg.ChunkIndex,
		arg.ChunkCount,
		arg.Text,
	)
	return err
}
