// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package querries

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.collectionWeightForChunkIDsStmt, err = db.PrepareContext(ctx, collectionWeightForChunkIDs); err != nil {
		return nil, fmt.Errorf("error preparing query CollectionWeightForChunkIDs: %w", err)
	}
	if q.createCollectionOrUpdateWeightStmt, err = db.PrepareContext(ctx, createCollectionOrUpdateWeight); err != nil {
		return nil, fmt.Errorf("error preparing query CreateCollectionOrUpdateWeight: %w", err)
	}
	if q.createDocumentStmt, err = db.PrepareContext(ctx, createDocument); err != nil {
		return nil, fmt.Errorf("error preparing query CreateDocument: %w", err)
	}
	if q.createExtractionStmt, err = db.PrepareContext(ctx, createExtraction); err != nil {
		return nil, fmt.Errorf("error preparing query CreateExtraction: %w", err)
	}
	if q.createExtractionNodeStmt, err = db.PrepareContext(ctx, createExtractionNode); err != nil {
		return nil, fmt.Errorf("error preparing query CreateExtractionNode: %w", err)
	}
	if q.docAlreadyChunkedStmt, err = db.PrepareContext(ctx, docAlreadyChunked); err != nil {
		return nil, fmt.Errorf("error preparing query DocAlreadyChunked: %w", err)
	}
	if q.existsDocumentStmt, err = db.PrepareContext(ctx, existsDocument); err != nil {
		return nil, fmt.Errorf("error preparing query ExistsDocument: %w", err)
	}
	if q.flushChunkNodesStmt, err = db.PrepareContext(ctx, flushChunkNodes); err != nil {
		return nil, fmt.Errorf("error preparing query FlushChunkNodes: %w", err)
	}
	if q.flushChunksStmt, err = db.PrepareContext(ctx, flushChunks); err != nil {
		return nil, fmt.Errorf("error preparing query FlushChunks: %w", err)
	}
	if q.getAllCollectionWeightsStmt, err = db.PrepareContext(ctx, getAllCollectionWeights); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllCollectionWeights: %w", err)
	}
	if q.getDocumentIDsAfterIDStmt, err = db.PrepareContext(ctx, getDocumentIDsAfterID); err != nil {
		return nil, fmt.Errorf("error preparing query GetDocumentIDsAfterID: %w", err)
	}
	if q.getLatestExtractionOfDocStmt, err = db.PrepareContext(ctx, getLatestExtractionOfDoc); err != nil {
		return nil, fmt.Errorf("error preparing query GetLatestExtractionOfDoc: %w", err)
	}
	if q.insertChunkStmt, err = db.PrepareContext(ctx, insertChunk); err != nil {
		return nil, fmt.Errorf("error preparing query InsertChunk: %w", err)
	}
	if q.insertChunkNodesStmt, err = db.PrepareContext(ctx, insertChunkNodes); err != nil {
		return nil, fmt.Errorf("error preparing query InsertChunkNodes: %w", err)
	}
	if q.retrievalChunksByIDsStmt, err = db.PrepareContext(ctx, retrievalChunksByIDs); err != nil {
		return nil, fmt.Errorf("error preparing query RetrievalChunksByIDs: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.collectionWeightForChunkIDsStmt != nil {
		if cerr := q.collectionWeightForChunkIDsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing collectionWeightForChunkIDsStmt: %w", cerr)
		}
	}
	if q.createCollectionOrUpdateWeightStmt != nil {
		if cerr := q.createCollectionOrUpdateWeightStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createCollectionOrUpdateWeightStmt: %w", cerr)
		}
	}
	if q.createDocumentStmt != nil {
		if cerr := q.createDocumentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createDocumentStmt: %w", cerr)
		}
	}
	if q.createExtractionStmt != nil {
		if cerr := q.createExtractionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createExtractionStmt: %w", cerr)
		}
	}
	if q.createExtractionNodeStmt != nil {
		if cerr := q.createExtractionNodeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createExtractionNodeStmt: %w", cerr)
		}
	}
	if q.docAlreadyChunkedStmt != nil {
		if cerr := q.docAlreadyChunkedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing docAlreadyChunkedStmt: %w", cerr)
		}
	}
	if q.existsDocumentStmt != nil {
		if cerr := q.existsDocumentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing existsDocumentStmt: %w", cerr)
		}
	}
	if q.flushChunkNodesStmt != nil {
		if cerr := q.flushChunkNodesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing flushChunkNodesStmt: %w", cerr)
		}
	}
	if q.flushChunksStmt != nil {
		if cerr := q.flushChunksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing flushChunksStmt: %w", cerr)
		}
	}
	if q.getAllCollectionWeightsStmt != nil {
		if cerr := q.getAllCollectionWeightsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllCollectionWeightsStmt: %w", cerr)
		}
	}
	if q.getDocumentIDsAfterIDStmt != nil {
		if cerr := q.getDocumentIDsAfterIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDocumentIDsAfterIDStmt: %w", cerr)
		}
	}
	if q.getLatestExtractionOfDocStmt != nil {
		if cerr := q.getLatestExtractionOfDocStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLatestExtractionOfDocStmt: %w", cerr)
		}
	}
	if q.insertChunkStmt != nil {
		if cerr := q.insertChunkStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertChunkStmt: %w", cerr)
		}
	}
	if q.insertChunkNodesStmt != nil {
		if cerr := q.insertChunkNodesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertChunkNodesStmt: %w", cerr)
		}
	}
	if q.retrievalChunksByIDsStmt != nil {
		if cerr := q.retrievalChunksByIDsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing retrievalChunksByIDsStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                 DBTX
	tx                                 *sql.Tx
	collectionWeightForChunkIDsStmt    *sql.Stmt
	createCollectionOrUpdateWeightStmt *sql.Stmt
	createDocumentStmt                 *sql.Stmt
	createExtractionStmt               *sql.Stmt
	createExtractionNodeStmt           *sql.Stmt
	docAlreadyChunkedStmt              *sql.Stmt
	existsDocumentStmt                 *sql.Stmt
	flushChunkNodesStmt                *sql.Stmt
	flushChunksStmt                    *sql.Stmt
	getAllCollectionWeightsStmt        *sql.Stmt
	getDocumentIDsAfterIDStmt          *sql.Stmt
	getLatestExtractionOfDocStmt       *sql.Stmt
	insertChunkStmt                    *sql.Stmt
	insertChunkNodesStmt               *sql.Stmt
	retrievalChunksByIDsStmt           *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                 tx,
		tx:                                 tx,
		collectionWeightForChunkIDsStmt:    q.collectionWeightForChunkIDsStmt,
		createCollectionOrUpdateWeightStmt: q.createCollectionOrUpdateWeightStmt,
		createDocumentStmt:                 q.createDocumentStmt,
		createExtractionStmt:               q.createExtractionStmt,
		createExtractionNodeStmt:           q.createExtractionNodeStmt,
		docAlreadyChunkedStmt:              q.docAlreadyChunkedStmt,
		existsDocumentStmt:                 q.existsDocumentStmt,
		flushChunkNodesStmt:                q.flushChunkNodesStmt,
		flushChunksStmt:                    q.flushChunksStmt,
		getAllCollectionWeightsStmt:        q.getAllCollectionWeightsStmt,
		getDocumentIDsAfterIDStmt:          q.getDocumentIDsAfterIDStmt,
		getLatestExtractionOfDocStmt:       q.getLatestExtractionOfDocStmt,
		insertChunkStmt:                    q.insertChunkStmt,
		insertChunkNodesStmt:               q.insertChunkNodesStmt,
		retrievalChunksByIDsStmt:           q.retrievalChunksByIDsStmt,
	}
}
