// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package querries

type Chunk struct {
	ID         int64
	DocumentID int64
	ChunkIndex int64
	ChunkCount int64
	Text       string
}

type Document struct {
	ID       int64
	Filename string
}
