// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package querries

import (
	"database/sql"
	"time"
)

type Chunk struct {
	ID         int64
	CreatedAt  time.Time
	DocumentID int64
	Position   int64
	Type       string
	Text       string
	Breadcrumb string
}

type ChunkNode struct {
	ChunkID          int64
	ExtractionNodeID int64
	CreatedAt        time.Time
	Position         int64
}

type Collection struct {
	Name   string
	Weight float64
}

type Document struct {
	ID             int64
	CreatedAt      time.Time
	Name           string
	Sha256         string
	MetadataJson   sql.NullString
	CollectionName string
}

type Extraction struct {
	ID         int64
	CreatedAt  time.Time
	DocumentID int64
	MimeType   string
}

type ExtractionNode struct {
	ID             int64
	CreatedAt      time.Time
	ExtractionID   int64
	NodeID         string
	ParentID       sql.NullString
	Kind           string
	Layer          string
	ContentJson    sql.NullString
	ProvenanceJson sql.NullString
}
