// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package querries

import (
	"database/sql"
	"time"
)

type Chunk struct {
	ID               int64
	CreatedAt        time.Time
	RepresentationID int64
	Position         int64
	Text             string
	Embedded         int64
}

type Document struct {
	ID           int64
	CreatedAt    time.Time
	Name         string
	Sha256       string
	MetadataJson sql.NullString
}

type Extraction struct {
	ID               int64
	CreatedAt        time.Time
	RepresentationID int64
	MimeType         string
	QualityScore     []byte
	MetadataJson     sql.NullString
}

type ExtractionNode struct {
	ID             int64
	CreatedAt      time.Time
	ExtractionID   int64
	NodeID         string
	ParentID       sql.NullString
	Kind           string
	Layer          string
	ContentJson    sql.NullString
	ProvenanceJson sql.NullString
}

type Representation struct {
	ID                     int64
	CreatedAt              time.Time
	DocumentID             int64
	ParentRepresentationID sql.NullInt64
	Stage                  string
}
