// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package querries

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const createChildRepresentationFromParent = `-- name: CreateChildRepresentationFromParent :one
INSERT INTO representations (
  document_id,
  parent_representation_id,
  stage,
  created_at
)
SELECT
  r.document_id,
  ?,
  ?,
  ?
FROM representations r
WHERE r.id = ?
RETURNING representations.id
`

type CreateChildRepresentationFromParentParams struct {
	ParentRepresentationID sql.NullInt64
	Stage                  string
	CreatedAt              time.Time
	ID                     int64
}

func (q *Queries) CreateChildRepresentationFromParent(ctx context.Context, arg CreateChildRepresentationFromParentParams) (int64, error) {
	row := q.queryRow(ctx, q.createChildRepresentationFromParentStmt, createChildRepresentationFromParent,
		arg.ParentRepresentationID,
		arg.Stage,
		arg.CreatedAt,
		arg.ID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createDocument = `-- name: CreateDocument :one

INSERT INTO documents (
	created_at,
	name,
	sha256,
	metadata_json
) VALUES (
	?,?,?,?
)
RETURNING id
`

type CreateDocumentParams struct {
	CreatedAt    time.Time
	Name         string
	Sha256       string
	MetadataJson sql.NullString
}

// TODO: in pakete auftrennen
func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (int64, error) {
	row := q.queryRow(ctx, q.createDocumentStmt, createDocument,
		arg.CreatedAt,
		arg.Name,
		arg.Sha256,
		arg.MetadataJson,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createExtraction = `-- name: CreateExtraction :one
INSERT INTO extractions (
	representation_id,
	created_at,
	mime_type
) VALUES (
	?,?,?
)
RETURNING id
`

type CreateExtractionParams struct {
	RepresentationID int64
	CreatedAt        time.Time
	MimeType         string
}

func (q *Queries) CreateExtraction(ctx context.Context, arg CreateExtractionParams) (int64, error) {
	row := q.queryRow(ctx, q.createExtractionStmt, createExtraction, arg.RepresentationID, arg.CreatedAt, arg.MimeType)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createExtractionNode = `-- name: CreateExtractionNode :exec
INSERT INTO extraction_nodes (
      extraction_id,
      created_at,
      node_id,
      parent_id,
      kind,
      layer,
      content_json,
      provenance_json
) VALUES (
      ?,?,?,?,?,?,?,?
)
`

type CreateExtractionNodeParams struct {
	ExtractionID   int64
	CreatedAt      time.Time
	NodeID         string
	ParentID       sql.NullString
	Kind           string
	Layer          string
	ContentJson    sql.NullString
	ProvenanceJson sql.NullString
}

func (q *Queries) CreateExtractionNode(ctx context.Context, arg CreateExtractionNodeParams) error {
	_, err := q.exec(ctx, q.createExtractionNodeStmt, createExtractionNode,
		arg.ExtractionID,
		arg.CreatedAt,
		arg.NodeID,
		arg.ParentID,
		arg.Kind,
		arg.Layer,
		arg.ContentJson,
		arg.ProvenanceJson,
	)
	return err
}

const createRepresentation = `-- name: CreateRepresentation :one
INSERT INTO representations (
	document_id,
	parent_representation_id,
	stage,
	created_at
) VALUES (
	?,?,?,?
)
RETURNING id
`

type CreateRepresentationParams struct {
	DocumentID             int64
	ParentRepresentationID sql.NullInt64
	Stage                  string
	CreatedAt              time.Time
}

func (q *Queries) CreateRepresentation(ctx context.Context, arg CreateRepresentationParams) (int64, error) {
	row := q.queryRow(ctx, q.createRepresentationStmt, createRepresentation,
		arg.DocumentID,
		arg.ParentRepresentationID,
		arg.Stage,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const existsDocument = `-- name: ExistsDocument :one
SELECT  id, sha256
FROM documents
WHERE sha256 = ?
`

type ExistsDocumentRow struct {
	ID     int64
	Sha256 string
}

func (q *Queries) ExistsDocument(ctx context.Context, sha256 string) (ExistsDocumentRow, error) {
	row := q.queryRow(ctx, q.existsDocumentStmt, existsDocument, sha256)
	var i ExistsDocumentRow
	err := row.Scan(&i.ID, &i.Sha256)
	return i, err
}

const getDocumentIDsAfterID = `-- name: GetDocumentIDsAfterID :one
SELECT id
FROM documents
WHERE  id > ?
ORDER BY id
`

func (q *Queries) GetDocumentIDsAfterID(ctx context.Context, id int64) (int64, error) {
	row := q.queryRow(ctx, q.getDocumentIDsAfterIDStmt, getDocumentIDsAfterID, id)
	err := row.Scan(&id)
	return id, err
}

const getLatestExtractionOfDoc = `-- name: GetLatestExtractionOfDoc :many
WITH latest_extraction AS (
  SELECT
    r.id AS representation_id,
    r.created_at AS representation_created_at,
    e.id AS extraction_id,
    e.mime_type
  FROM representations r
  JOIN extractions e
    ON e.representation_id = r.id
  WHERE r.document_id = ?
    AND r.stage = 'extract'
  ORDER BY r.created_at DESC, r.id DESC
  LIMIT 1
)
SELECT
  le.representation_id,
  le.representation_created_at,
  le.mime_type,
  en.id, en.created_at, en.extraction_id, en.node_id, en.parent_id, en.kind, en.layer, en.content_json, en.provenance_json
FROM latest_extraction le
JOIN extraction_nodes en
  ON en.extraction_id = le.extraction_id
ORDER BY en.id
`

type GetLatestExtractionOfDocRow struct {
	RepresentationID        int64
	RepresentationCreatedAt time.Time
	MimeType                string
	ID                      int64
	CreatedAt               time.Time
	ExtractionID            int64
	NodeID                  string
	ParentID                sql.NullString
	Kind                    string
	Layer                   string
	ContentJson             sql.NullString
	ProvenanceJson          sql.NullString
}

func (q *Queries) GetLatestExtractionOfDoc(ctx context.Context, documentID int64) ([]GetLatestExtractionOfDocRow, error) {
	rows, err := q.query(ctx, q.getLatestExtractionOfDocStmt, getLatestExtractionOfDoc, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLatestExtractionOfDocRow
	for rows.Next() {
		var i GetLatestExtractionOfDocRow
		if err := rows.Scan(
			&i.RepresentationID,
			&i.RepresentationCreatedAt,
			&i.MimeType,
			&i.ID,
			&i.CreatedAt,
			&i.ExtractionID,
			&i.NodeID,
			&i.ParentID,
			&i.Kind,
			&i.Layer,
			&i.ContentJson,
			&i.ProvenanceJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertChunk = `-- name: InsertChunk :exec
INSERT INTO chunks (
	representation_id,
	position,
	text,
	breadcrumb,
	created_at
) VALUES (?,?,?,?,?)
`

type InsertChunkParams struct {
	RepresentationID int64
	Position         int64
	Text             string
	Breadcrumb       string
	CreatedAt        time.Time
}

func (q *Queries) InsertChunk(ctx context.Context, arg InsertChunkParams) error {
	_, err := q.exec(ctx, q.insertChunkStmt, insertChunk,
		arg.RepresentationID,
		arg.Position,
		arg.Text,
		arg.Breadcrumb,
		arg.CreatedAt,
	)
	return err
}

const retrievalChunksByIDs = `-- name: RetrievalChunksByIDs :many
SELECT c.id, d.name, c.position, c.text
FROM chunks AS c
JOIN representations r ON r.id = c.representation_id
JOIN documents d ON d.id = r.document_id
WHERE c.id IN (/*SLICE:chunk_ids*/?)
`

type RetrievalChunksByIDsRow struct {
	ID       int64
	Name     string
	Position int64
	Text     string
}

func (q *Queries) RetrievalChunksByIDs(ctx context.Context, chunkIds []int64) ([]RetrievalChunksByIDsRow, error) {
	query := retrievalChunksByIDs
	var queryParams []interface{}
	if len(chunkIds) > 0 {
		for _, v := range chunkIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:chunk_ids*/?", strings.Repeat(",?", len(chunkIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:chunk_ids*/?", "NULL", 1)
	}
	rows, err := q.query(ctx, nil, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RetrievalChunksByIDsRow
	for rows.Next() {
		var i RetrievalChunksByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Position,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
