// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package querries

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const collectionWeightForChunkIDs = `-- name: CollectionWeightForChunkIDs :many
SELECT chunks.id, collections.weight
FROM chunks
JOIN documents
ON chunks.document_id = documents.id
JOIN collections
ON documents.collection_name = collections.name
WHERE chunks.id IN (/*SLICE:chunk_ids*/?)
`

type CollectionWeightForChunkIDsRow struct {
	ID     int64
	Weight float64
}

func (q *Queries) CollectionWeightForChunkIDs(ctx context.Context, chunkIds []int64) ([]CollectionWeightForChunkIDsRow, error) {
	query := collectionWeightForChunkIDs
	var queryParams []interface{}
	if len(chunkIds) > 0 {
		for _, v := range chunkIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:chunk_ids*/?", strings.Repeat(",?", len(chunkIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:chunk_ids*/?", "NULL", 1)
	}
	rows, err := q.query(ctx, nil, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CollectionWeightForChunkIDsRow
	for rows.Next() {
		var i CollectionWeightForChunkIDsRow
		if err := rows.Scan(&i.ID, &i.Weight); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createCollectionOrUpdateWeight = `-- name: CreateCollectionOrUpdateWeight :exec
INSERT INTO collections (
	name,
	weight
) VALUES (?,?)
ON CONFLICT DO
UPDATE SET weight = excluded.weight
`

type CreateCollectionOrUpdateWeightParams struct {
	Name   string
	Weight float64
}

func (q *Queries) CreateCollectionOrUpdateWeight(ctx context.Context, arg CreateCollectionOrUpdateWeightParams) error {
	_, err := q.exec(ctx, q.createCollectionOrUpdateWeightStmt, createCollectionOrUpdateWeight, arg.Name, arg.Weight)
	return err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (
	created_at,
	name,
	sha256,
	collection_name,
	metadata_json
) VALUES (
	?,?,?,?,?
)
RETURNING id
`

type CreateDocumentParams struct {
	CreatedAt      time.Time
	Name           string
	Sha256         string
	CollectionName string
	MetadataJson   sql.NullString
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (int64, error) {
	row := q.queryRow(ctx, q.createDocumentStmt, createDocument,
		arg.CreatedAt,
		arg.Name,
		arg.Sha256,
		arg.CollectionName,
		arg.MetadataJson,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createExtraction = `-- name: CreateExtraction :one
INSERT INTO extractions (
	document_id,
	created_at,
	mime_type
) VALUES (
	?,?,?
)
RETURNING id
`

type CreateExtractionParams struct {
	DocumentID int64
	CreatedAt  time.Time
	MimeType   string
}

func (q *Queries) CreateExtraction(ctx context.Context, arg CreateExtractionParams) (int64, error) {
	row := q.queryRow(ctx, q.createExtractionStmt, createExtraction, arg.DocumentID, arg.CreatedAt, arg.MimeType)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createExtractionNode = `-- name: CreateExtractionNode :exec
INSERT INTO extraction_nodes (
      extraction_id,
      created_at,
      node_id,
      parent_id,
      kind,
      layer,
      content_json,
      provenance_json
) VALUES (
      ?,?,?,?,?,?,?,?
)
`

type CreateExtractionNodeParams struct {
	ExtractionID   int64
	CreatedAt      time.Time
	NodeID         string
	ParentID       sql.NullString
	Kind           string
	Layer          string
	ContentJson    sql.NullString
	ProvenanceJson sql.NullString
}

func (q *Queries) CreateExtractionNode(ctx context.Context, arg CreateExtractionNodeParams) error {
	_, err := q.exec(ctx, q.createExtractionNodeStmt, createExtractionNode,
		arg.ExtractionID,
		arg.CreatedAt,
		arg.NodeID,
		arg.ParentID,
		arg.Kind,
		arg.Layer,
		arg.ContentJson,
		arg.ProvenanceJson,
	)
	return err
}

const docAlreadyChunked = `-- name: DocAlreadyChunked :one
SELECT id
FROM chunks
WHERE document_id = ?
LIMIT 1
`

func (q *Queries) DocAlreadyChunked(ctx context.Context, documentID int64) (int64, error) {
	row := q.queryRow(ctx, q.docAlreadyChunkedStmt, docAlreadyChunked, documentID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const existsDocument = `-- name: ExistsDocument :one
SELECT  d.id, d.sha256, c.name AS collection_name
FROM documents d
JOIN collections c
ON d.collection_name = c.name
WHERE d.sha256 = ?
`

type ExistsDocumentRow struct {
	ID             int64
	Sha256         string
	CollectionName string
}

func (q *Queries) ExistsDocument(ctx context.Context, sha256 string) (ExistsDocumentRow, error) {
	row := q.queryRow(ctx, q.existsDocumentStmt, existsDocument, sha256)
	var i ExistsDocumentRow
	err := row.Scan(&i.ID, &i.Sha256, &i.CollectionName)
	return i, err
}

const flushChunks = `-- name: FlushChunks :exec
DELETE FROM chunks
`

func (q *Queries) FlushChunks(ctx context.Context) error {
	_, err := q.exec(ctx, q.flushChunksStmt, flushChunks)
	return err
}

const getAllCollectionWeights = `-- name: GetAllCollectionWeights :many
SELECT name, weight FROM collections
`

func (q *Queries) GetAllCollectionWeights(ctx context.Context) ([]Collection, error) {
	rows, err := q.query(ctx, q.getAllCollectionWeightsStmt, getAllCollectionWeights)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Collection
	for rows.Next() {
		var i Collection
		if err := rows.Scan(&i.Name, &i.Weight); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocumentIDsAfterID = `-- name: GetDocumentIDsAfterID :one
SELECT id
FROM documents
WHERE  id > ?
ORDER BY id
`

func (q *Queries) GetDocumentIDsAfterID(ctx context.Context, id int64) (int64, error) {
	row := q.queryRow(ctx, q.getDocumentIDsAfterIDStmt, getDocumentIDsAfterID, id)
	err := row.Scan(&id)
	return id, err
}

const getLatestExtractionOfDoc = `-- name: GetLatestExtractionOfDoc :many
SELECT
	e.id AS extraction_id,
	e.document_id,
	e.mime_type,
	en.id AS extraction_node_id,
	en.node_id,
	en.parent_id,
	en.kind,
	en.layer,
	en.provenance_json,
	en.content_json
FROM extractions e
JOIN extraction_nodes en
	ON en.extraction_id = e.id
WHERE e.document_id = ?
ORDER BY en.id
`

type GetLatestExtractionOfDocRow struct {
	ExtractionID     int64
	DocumentID       int64
	MimeType         string
	ExtractionNodeID int64
	NodeID           string
	ParentID         sql.NullString
	Kind             string
	Layer            string
	ProvenanceJson   sql.NullString
	ContentJson      sql.NullString
}

func (q *Queries) GetLatestExtractionOfDoc(ctx context.Context, documentID int64) ([]GetLatestExtractionOfDocRow, error) {
	rows, err := q.query(ctx, q.getLatestExtractionOfDocStmt, getLatestExtractionOfDoc, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLatestExtractionOfDocRow
	for rows.Next() {
		var i GetLatestExtractionOfDocRow
		if err := rows.Scan(
			&i.ExtractionID,
			&i.DocumentID,
			&i.MimeType,
			&i.ExtractionNodeID,
			&i.NodeID,
			&i.ParentID,
			&i.Kind,
			&i.Layer,
			&i.ProvenanceJson,
			&i.ContentJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertChunk = `-- name: InsertChunk :one
INSERT INTO chunks (
	document_id,
	position,
	type,
	text,
	breadcrumb,
	created_at
) VALUES (?,?,?,?,?,?)
RETURNING id
`

type InsertChunkParams struct {
	DocumentID int64
	Position   int64
	Type       string
	Text       string
	Breadcrumb string
	CreatedAt  time.Time
}

func (q *Queries) InsertChunk(ctx context.Context, arg InsertChunkParams) (int64, error) {
	row := q.queryRow(ctx, q.insertChunkStmt, insertChunk,
		arg.DocumentID,
		arg.Position,
		arg.Type,
		arg.Text,
		arg.Breadcrumb,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertChunkNodes = `-- name: InsertChunkNodes :exec
INSERT INTO chunk_nodes(
	chunk_id,
	extraction_node_id,
	created_at,
	position
) VALUES(?,?,?,?)
`

type InsertChunkNodesParams struct {
	ChunkID          int64
	ExtractionNodeID int64
	CreatedAt        time.Time
	Position         int64
}

func (q *Queries) InsertChunkNodes(ctx context.Context, arg InsertChunkNodesParams) error {
	_, err := q.exec(ctx, q.insertChunkNodesStmt, insertChunkNodes,
		arg.ChunkID,
		arg.ExtractionNodeID,
		arg.CreatedAt,
		arg.Position,
	)
	return err
}

const retrievalChunksByIDs = `-- name: RetrievalChunksByIDs :many
SELECT c.id, d.name, d.collection_name, c.position, c.breadcrumb, c.text
FROM chunks AS c
JOIN documents AS d
	ON c.document_id = d.id
WHERE c.id IN (/*SLICE:chunk_ids*/?)
`

type RetrievalChunksByIDsRow struct {
	ID             int64
	Name           string
	CollectionName string
	Position       int64
	Breadcrumb     string
	Text           string
}

func (q *Queries) RetrievalChunksByIDs(ctx context.Context, chunkIds []int64) ([]RetrievalChunksByIDsRow, error) {
	query := retrievalChunksByIDs
	var queryParams []interface{}
	if len(chunkIds) > 0 {
		for _, v := range chunkIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:chunk_ids*/?", strings.Repeat(",?", len(chunkIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:chunk_ids*/?", "NULL", 1)
	}
	rows, err := q.query(ctx, nil, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RetrievalChunksByIDsRow
	for rows.Next() {
		var i RetrievalChunksByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CollectionName,
			&i.Position,
			&i.Breadcrumb,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
