// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package retrieve

import (
	"context"
	"strings"
)

const getChunksForIDs = `-- name: GetChunksForIDs :many
SELECT c.id, c.chunk_count, c.text, c.chunk_index, c.document_id, d.filename FROM chunks AS c
	JOIN documents AS d
	ON c.document_id = d.id
	WHERE c.id IN (/*SLICE:ids*/?)
`

type GetChunksForIDsRow struct {
	ID         int64
	ChunkCount int64
	Text       string
	ChunkIndex int64
	DocumentID int64
	Filename   string
}

func (q *Queries) GetChunksForIDs(ctx context.Context, ids []int64) ([]GetChunksForIDsRow, error) {
	query := getChunksForIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChunksForIDsRow
	for rows.Next() {
		var i GetChunksForIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.ChunkCount,
			&i.Text,
			&i.ChunkIndex,
			&i.DocumentID,
			&i.Filename,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
